disabled_rules: # rule identifiers to exclude from running
  - colon
  - opening_brace

opt_in_rules:
- empty_count
- missing_docs
- force_unwrapping

force_unwrapping: error

file_length:
  warning: 500
  error: 2500

function_body_length:
  - 200 #warning
  - 300 #error

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names

type_name:
  min_length: 4.swiftlint.yml # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
  - iPhone # excluded via string
  - API
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - vc
    - id
    - url
    - URL
    - API
    - app
    - key
    - tap
    - new
    - sms
    - hex
    - row
    - jwt
    - txt
    - day
    - old
    - moq
    - faq
    - USD
    - EUR
    - nib
    - dot
    - i
    - to
    - fm
    - log
    - lhs
    - rhs
    - x
    - y
    - up
    - big
    - tip
    - dev
    - GET
    - top
    - one
    - two
    - six
    - ten
    - pop
    - set
    - me
    - cvc

line_length:
  warning: 180
  error: 250
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ### works up until this config rule
  ignores_interpolated_strings: true

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ${SRCROOT}/Carthage
  - ${SRCROOT}/Pods

custom_rules:
    open_iboutlets:
      included: ".*\\.swift"
      name: "IBOutlet opening"
      regex: '@IBOutlet ?(weak){0,1} var'
      message: "IBOutlet should be private"
      severity: error

    open_ibaction:
      included: ".*\\.swift"
      name: "IBAction opening"
      regex: '@IBAction func'
      message: "IBAction should be private"
      severity: error

    debug_rule:
      regex: 'print'
      message: "Print decrease performance of the app"
      severity: error

    numbers_notGood:
      regex: '(return |case |\w\(|: |\?\? |\, |== |<=? |>=? |\+= |\-= |\/= |\*= |%= |\w\.\w+ = )\(*\d{2,}'
      message: "Numbers not good; define a constant instead."

    foundation_using:
      regex: 'import Foundation'
      message: "Do you really need for Foundation ???"


reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
